const ipServices = [
  "https://wtfismyip.com/json",
  "https://myip.wtf/json",
  "https://api.my-ip.io/v2/ip.json",
  "https://check.torproject.org/api/ip",
  "https://httpbin.org/ip",
  "https://ifconfig.pro/ip.host",
  "https://iphorse.com/json",
  "https://ipapi.co/json",
  "https://api.ip2location.io",
  "https://ifconfig.co/json",
  "https://ipaddr.site",
  "https://checkip.amazonaws.com",
  "https://ident.me",
  "https://whatismyip.akamai.com",
  "https://ipv4.text.wtfismyip.com",
  "https://api.ipify.org",
  "https://l2.io/ip",
  "https://curlmyip.net",
  "https://ifconfig.io/ip",
  "https://ifconfig.es",
  "https://ipaddress.sh",
  "https://eth0.me",
  "https://ipinfo.io/ip",
  "https://icanhazip.com",
  "https://ip.liquidweb.com",
  //  "https://ipaddy.net",
] as const;

export default ipServices;
